#!/bin/bash

set -e              # Willexit immediate if command exits with non-zero status
set -u              # Will print message if variable not set,
set -o pipefail     # Fail on a pipline like cmd1 | cmd2 | cmd3, rather then wait

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

exit 1

jq -n "{}" >&3